# Set the build language to Python
language: python
python: 
  - 3.7
# Define executable
install:
  - pip3 install codecov
# Run the tests
script:
  - coverage3 run start.py
# Push results to codecov (token set in config)
after_success:
  - codecov