# Set the build language to Python
language: python
python: 
  - 3.7
# Install necessary packages
install:
  - pip install -r requirements.txt
# Define executable
script:
  - coverage run start.py
# Push results to codecov (token set in config)
after_success:
  - codecov